# Generated by Django 3.2.12 on 2022-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuserprofile_download_resets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='download_resets',
        ),
        migrations.AddField(
            model_name='customuser',
            name='download_resets',
            field=models.SmallIntegerField(default=0, verbose_name='Download resets'),
        ),
    ]
