# Generated by Django 3.2.12 on 2022-02-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20220220_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastcontentpage',
            name='episode_type',
            field=models.CharField(blank=True, choices=[('bonus', 'Bonus'), ('trailer', 'Trailer')], help_text='Optional, is this a bonus? Or a trailer episode outside the normal sequence? Leave blank if neither.', max_length=10, null=True, verbose_name='Episode type'),
        ),
    ]
