# Generated by Django 3.2.12 on 2022-02-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20220221_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='download_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
