# Generated by Django 3.2.12 on 2022-02-21 15:53

import custom_storages
from django.db import migrations, models
import website.utils


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_download_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommedia',
            name='file',
            field=models.FileField(storage=custom_storages.PrivMediaStorage(), upload_to=website.utils.slugify_filename, verbose_name='file'),
        ),
    ]
