# Generated by Django 3.2.12 on 2022-03-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontentpage',
            name='front_page',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Show on home page list?', verbose_name='Front page?'),
        ),
        migrations.AddField(
            model_name='podcastcontentpage',
            name='front_page',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text='Show on home page list?', verbose_name='Front page?'),
        ),
    ]