# Generated by Django 3.2.12 on 2022-03-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('website', '0011_auto_20220309_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecontentindexpage',
            name='rss_premium_image',
            field=models.ForeignKey(help_text='The RSS image which will appear for premium feed users on the paid tier(s)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='RSS premium image'),
        ),
        migrations.AddField(
            model_name='podcastcontentindexpage',
            name='rss_premium_image',
            field=models.ForeignKey(help_text='The RSS image which will appear for premium feed users on the paid tier(s)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='RSS premium image'),
        ),
    ]
