# Generated by Django 3.2.12 on 2022-04-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20220313_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='apple_podcasts',
            field=models.URLField(blank=True, help_text='Your Apple Podcasts URL', verbose_name='Apple Podcasts'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='google_podcasts',
            field=models.URLField(blank=True, help_text='Your Google Podcasts URL', verbose_name='Google Podcasts'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='spotify',
            field=models.URLField(blank=True, help_text='Your Spotify podcast URL', verbose_name='Spotify'),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='stitcher',
            field=models.URLField(blank=True, help_text='Your Stitcher podcast URL', verbose_name='Stitcher'),
        ),
    ]