# Generated by Django 3.2.12 on 2022-04-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20220404_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticssettings',
            name='ga_tag_manager_id',
            field=models.CharField(blank=True, help_text='Your Google Tag Manager ID if you wish to track clicks.', max_length=255, null=True, verbose_name='Google Tag Manager ID'),
        ),
    ]
