max_parallel_worker_cpus: "{{ (ansible_processor_vcpus|int - 2) | int }}"
max_parallel_gather_cpus: "4"
pgsql_work_mem: "{{ (((((ansible_memtotal_mb|int * 256) / 100) * ansible_processor_vcpus|int) * (ansible_memtotal_mb|int / 1024)) | round | int }}"